"""Admin UI — authentication, container logs, request inspector, source config guide."""

import asyncio
import hashlib
import hmac
import json
import os
import secrets
import time
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Cookie, Form, Request
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse, Response, StreamingResponse

from trace import REQUEST_TRACE

# ── Config ────────────────────────────────────────────────────────────────────
ADMIN_USER   = os.environ.get("ADMIN_USERNAME", "admin")
ADMIN_PASS   = os.environ.get("ADMIN_PASSWORD", "apigenie")
ADMIN_HASH   = os.environ.get("ADMIN_PASSWORD_HASH", "").strip()
SESSION_TTL  = 86400  # 24 h
COOKIE       = "ag_session"

# Override file for the admin password hash, written by the in-app "change
# password" form. Persists across container restarts when /var/lib/apigenie
# is volume-mounted. Takes precedence over ADMIN_PASSWORD_HASH env var.
ADMIN_PASSWORD_FILE = Path(os.environ.get("ADMIN_PASSWORD_FILE", "/var/lib/apigenie/admin_pass"))

# Public-facing hostname collectors will use to reach this stack. Required at
# import time because the SOURCES reference dict (curl examples, advertised
# endpoint URLs) is built once at startup.
DOMAIN       = os.environ.get("APIGENIE_DOMAIN", "apigenie.example.com")
TLS_MODE     = os.environ.get("APIGENIE_TLS_MODE", "unknown")
KAFKA_HOST   = os.environ.get("APIGENIE_KAFKA_ADVERTISED_HOST", DOMAIN)


# ── Password hashing (PBKDF2-HMAC-SHA256) ────────────────────────────────────
# Format:  pbkdf2_sha256$<iterations>$<salt_hex>$<hash_hex>
# Generated by scripts/hash_password.py and the admin Settings tab. Verified
# in constant time via hmac.compare_digest.
_PBKDF2_ITERATIONS = 600_000
_PBKDF2_DKLEN = 32
_PBKDF2_SALT_BYTES = 16


def _hash_password(plain: str) -> str:
    salt = secrets.token_bytes(_PBKDF2_SALT_BYTES)
    dk = hashlib.pbkdf2_hmac(
        "sha256", plain.encode("utf-8"), salt, _PBKDF2_ITERATIONS, dklen=_PBKDF2_DKLEN
    )
    return f"pbkdf2_sha256${_PBKDF2_ITERATIONS}${salt.hex()}${dk.hex()}"


def _verify_password_hash(plain: str, encoded: str) -> bool:
    try:
        scheme, iters_str, salt_hex, hash_hex = encoded.split("$", 3)
    except ValueError:
        return False
    if scheme != "pbkdf2_sha256":
        return False
    try:
        iters = int(iters_str)
        salt = bytes.fromhex(salt_hex)
        expected = bytes.fromhex(hash_hex)
    except ValueError:
        return False
    actual = hashlib.pbkdf2_hmac("sha256", plain.encode("utf-8"), salt, iters, dklen=len(expected))
    return hmac.compare_digest(actual, expected)


def _current_admin_hash() -> str:
    """Resolve the active admin hash: override file > env var > empty."""
    try:
        if ADMIN_PASSWORD_FILE.is_file():
            return ADMIN_PASSWORD_FILE.read_text(encoding="utf-8").strip()
    except OSError:
        pass
    return ADMIN_HASH


def _check_password(plain: str) -> bool:
    active_hash = _current_admin_hash()
    if active_hash:
        return _verify_password_hash(plain, active_hash)
    # Plaintext fallback for first-boot only. constant-time compare.
    return bool(ADMIN_PASS) and hmac.compare_digest(plain, ADMIN_PASS)

router = APIRouter(prefix="/admin", tags=["admin"])

_sessions: dict[str, float] = {}   # token → expires_at


def _new_session() -> str:
    tok = secrets.token_urlsafe(32)
    _sessions[tok] = time.time() + SESSION_TTL
    return tok


def _valid(token: str | None) -> bool:
    if not token:
        return False
    exp = _sessions.get(token)
    if not exp or time.time() > exp:
        _sessions.pop(token, None)
        return False
    return True


# ── Source config reference ───────────────────────────────────────────────────
BASE = f"https://{DOMAIN}"

SOURCES: dict[str, dict[str, Any]] = {
    "okta": {
        "name": "Okta",
        "auth_type": "Bearer token",
        "credentials": {"token": "apigenie-valid-token-001"},
        "endpoints": [
            {"method": "GET",  "path": "/api/v1/logs",  "desc": "System event logs"},
        ],
        "curl": f'curl -s -H "Authorization: Bearer apigenie-valid-token-001" \\\n  "{BASE}/api/v1/logs?limit=5"',
    },
    "netskope": {
        "name": "Netskope",
        "auth_type": "Bearer token",
        "credentials": {"token": "apigenie-valid-token-001"},
        "endpoints": [
            {"method": "GET", "path": "/api/v2/events/data/alert", "desc": "Alert events"},
            {"method": "GET", "path": "/api/v2/events/data/audit", "desc": "Audit events"},
        ],
        "curl": f'curl -s -H "Authorization: Bearer apigenie-valid-token-001" \\\n  "{BASE}/api/v2/events/data/alert?limit=5"',
    },
    "entra_id": {
        "name": "Microsoft Entra ID",
        "auth_type": "OAuth2 Bearer (tenant token endpoint)",
        "credentials": {
            "token_url": f"{BASE}/oauth2/v2.0/token  (or /{'{tenant-id}'}/oauth2/v2.0/token)",
            "token": "apigenie-valid-token-001",
        },
        "endpoints": [
            {"method": "POST", "path": "/oauth2/v2.0/token",                  "desc": "Get access token"},
            {"method": "GET",  "path": "/v1.0/auditLogs/directoryAudits",      "desc": "Directory audit logs"},
            {"method": "GET",  "path": "/v1.0/auditLogs/signIns",              "desc": "Sign-in logs"},
        ],
        "curl": f'curl -s -H "Authorization: Bearer apigenie-valid-token-001" \\\n  "{BASE}/v1.0/auditLogs/directoryAudits?\\$top=5"',
    },
    "defender": {
        "name": "Microsoft Defender",
        "auth_type": "Bearer token",
        "credentials": {"token": "apigenie-valid-token-001"},
        "endpoints": [
            {"method": "GET", "path": "/subscriptions/{sub_id}/providers/Microsoft.Security/alerts",          "desc": "Security alerts"},
            {"method": "GET", "path": "/subscriptions/{sub_id}/providers/Microsoft.Security/recommendations", "desc": "Recommendations"},
        ],
        "curl": (
            f'curl -s -H "Authorization: Bearer apigenie-valid-token-001" \\\n'
            f'  "{BASE}/subscriptions/00000000-0000-0000-0000-000000000001'
            f'/providers/Microsoft.Security/alerts"'
        ),
    },
    "cisco_duo": {
        "name": "Cisco Duo",
        "auth_type": "HTTP Basic (HMAC-SHA1 — ikey as username, computed sig as password)",
        "credentials": {
            "ikey": "DIXXXXXXXXXXXXXXXXXX",
            "skey": "duo-mock-secret-key-for-testing",
            "shortcut": "pass ikey as username with empty password to skip HMAC check",
        },
        "endpoints": [
            {"method": "GET", "path": "/admin/v1/logs/authentication", "desc": "Auth logs (v1)"},
            {"method": "GET", "path": "/admin/v2/logs/authentication", "desc": "Auth logs (v2, ms timestamps)"},
            {"method": "GET", "path": "/admin/v1/logs/administrator",  "desc": "Admin action logs"},
            {"method": "GET", "path": "/admin/v1/info/summary",        "desc": "Account summary"},
        ],
        "curl": f'curl -s -u "DIXXXXXXXXXXXXXXXXXX:" \\\n  "{BASE}/admin/v1/logs/authentication?limit=5"',
    },
    "gcp_audit": {
        "name": "GCP Cloud Logging",
        "auth_type": "Bearer token",
        "credentials": {"token": "apigenie-valid-token-001"},
        "endpoints": [
            {"method": "POST", "path": "/v2/entries:list", "desc": "List log entries"},
        ],
        "curl": (
            f'curl -s -X POST \\\n'
            f'  -H "Authorization: Bearer apigenie-valid-token-001" \\\n'
            f'  -H "Content-Type: application/json" \\\n'
            f'  -d \'{{"pageSize":5}}\' \\\n'
            f'  "{BASE}/v2/entries:list"'
        ),
    },
    "tenable": {
        "name": "Tenable",
        "auth_type": "X-ApiKeys header (accessKey + secretKey)",
        "credentials": {
            "accessKey": "apigenie-ak-001",
            "secretKey": "apigenie-sk-001",
            "header": "X-ApiKeys: accessKey=apigenie-ak-001;secretKey=apigenie-sk-001",
        },
        "endpoints": [
            {"method": "POST", "path": "/vulns/export",                      "desc": "Start vuln export → returns export_uuid"},
            {"method": "GET",  "path": "/vulns/export/{uuid}/status",         "desc": "Poll export status"},
            {"method": "GET",  "path": "/vulns/export/{uuid}/chunks/{id}",    "desc": "Download chunk"},
            {"method": "POST", "path": "/assets/export",                      "desc": "Start asset export"},
            {"method": "GET",  "path": "/audit-log/v1/events",               "desc": "Audit log events"},
        ],
        "curl": (
            f'curl -s \\\n'
            f'  -H "X-ApiKeys: accessKey=apigenie-ak-001;secretKey=apigenie-sk-001" \\\n'
            f'  "{BASE}/audit-log/v1/events?limit=5"'
        ),
    },
    "proofpoint": {
        "name": "Proofpoint TAP",
        "auth_type": "HTTP Basic auth",
        "credentials": {
            "username": "apigenie-principal-001",
            "password": "apigenie-secret-001",
        },
        "endpoints": [
            {"method": "GET", "path": "/v2/siem/all",              "desc": "All SIEM events"},
            {"method": "GET", "path": "/v2/siem/messages/blocked", "desc": "Blocked messages"},
            {"method": "GET", "path": "/v2/siem/clicks/blocked",   "desc": "Blocked clicks"},
        ],
        "curl": f'curl -s -u "apigenie-principal-001:apigenie-secret-001" \\\n  "{BASE}/v2/siem/all?sinceSeconds=3600"',
    },
    # AWS sources (CloudTrail, WAF, GuardDuty) intentionally omitted: real Observo
    # collectors fetch them via SQS-notified S3 polling, which requires LocalStack
    # (S3 + SQS) emulation rather than HTTP endpoints. Data generators remain in
    # sources/aws_*.py for that future integration. See docs/LOCALSTACK_PLAN.md.
    "wiz": {
        "name": "Wiz",
        "auth_type": "Bearer token + OAuth2",
        "credentials": {
            "token_url": f"{BASE}/oauth2/token",
            "token": "apigenie-valid-token-001",
        },
        "endpoints": [
            {"method": "POST", "path": "/oauth2/token", "desc": "Get access token"},
            {"method": "POST", "path": "/graphql",      "desc": "Issues via GraphQL"},
        ],
        "curl": (
            f'curl -s -X POST \\\n'
            f'  -H "Authorization: Bearer apigenie-valid-token-001" \\\n'
            f'  -H "Content-Type: application/json" \\\n'
            f'  -d \'{{"query":"{{ issues {{ id severity title }} }}","variables":{{"first":5}}}}\' \\\n'
            f'  "{BASE}/graphql"'
        ),
    },
    "snyk": {
        "name": "Snyk",
        "auth_type": "Bearer token",
        "credentials": {"token": "apigenie-valid-token-001"},
        "endpoints": [
            {"method": "GET", "path": "/v1/org/{org_id}/issues",   "desc": "Org issues"},
            {"method": "GET", "path": "/v1/org/{org_id}/projects",  "desc": "Org projects"},
            {"method": "GET", "path": "/v1/org/{org_id}/audit",     "desc": "Audit log"},
            {"method": "GET", "path": "/rest/orgs/{org_id}/issues", "desc": "Issues (REST API)"},
        ],
        "curl": (
            f'curl -s -H "Authorization: Bearer apigenie-valid-token-001" \\\n'
            f'  "{BASE}/v1/org/00000000-0000-0000-0000-000000000001/issues"'
        ),
    },
    "azure_platform": {
        "name": "Azure Platform (Event Hubs)",
        "auth_type": "Kafka SASL/PLAIN — username '$ConnectionString'",
        "credentials": {
            "Bootstrap servers (SASL_SSL)":   f"{DOMAIN}:9093",
            "Bootstrap servers (SASL_PLAINTEXT, no TLS)": f"{DOMAIN}:9094",
            "SASL mechanism": "PLAIN",
            "SASL username":  "$ConnectionString",
            "SASL password (= Connection String)": f"Endpoint=sb://{DOMAIN}/;SharedAccessKeyName=mock;SharedAccessKey=apigenie-eh-mock-2026;EntityPath=azure-platform-logs",
            "Topic / Event Hub name": "azure-platform-logs",
            "Consumer group": "any (e.g. observo-az)",
            "Override for SASL_PLAINTEXT": "Advanced Settings → librdkafka options → security.protocol=sasl_plaintext",
        },
        "endpoints": [
            {"method": "KAFKA", "path": ":9093 (SASL_SSL)",       "desc": "Real Azure Event Hubs shape — no overrides needed"},
            {"method": "KAFKA", "path": ":9094 (SASL_PLAINTEXT)", "desc": "Same auth, no TLS — set security.protocol=sasl_plaintext in Advanced Settings"},
            {"method": "KAFKA", "path": ":9092 (PLAINTEXT)",      "desc": "Legacy plain Kafka — no SASL"},
        ],
        "curl": (
            f'kcat -b {DOMAIN}:9094 -t azure-platform-logs -C \\\n'
            '  -X security.protocol=SASL_PLAINTEXT -X sasl.mechanism=PLAIN \\\n'
            '  -X sasl.username=\'$ConnectionString\' \\\n'
            f'  -X sasl.password=\'Endpoint=sb://{DOMAIN}/;SharedAccessKeyName=mock;SharedAccessKey=apigenie-eh-mock-2026;EntityPath=azure-platform-logs\''
        ),
    },
    "gcp_audit": {
        "name": "GCP Cloud Logging (Pub/Sub emulator)",
        "auth_type": "Service-account JSON (dummy) or PUBSUB_EMULATOR_HOST",
        "credentials": {
            "Pub/Sub endpoint (TLS, recommended for Observo)": f"{DOMAIN}:8443",
            "Pub/Sub endpoint (plaintext, emulator-aware SDKs)": f"{DOMAIN}:8085",
            "Project ID":       "obs-test",
            "Topic":            "audit-logs",
            "Subscription":     "audit-logs-sub",
            "Service-account JSON": "Download from /admin/gcp-sa.json (regenerated per process; never persisted)",
            "OAuth2 Token URI": f"https://{DOMAIN}/oauth2/token (already baked into the SA JSON)",
        },
        "endpoints": [
            {"method": "GRPC",  "path": ":8443 (TLS)",      "desc": "TLS-terminating nginx in front of Pub/Sub emulator — use this for Observo"},
            {"method": "GRPC",  "path": ":8085 (plaintext)", "desc": "Direct emulator port — only for clients that honour PUBSUB_EMULATOR_HOST"},
            {"method": "POST",  "path": "/oauth2/token",    "desc": "Fake Google OAuth2 endpoint (keeps non-emulator-aware clients happy)"},
        ],
        "curl": (
            f'PUBSUB_EMULATOR_HOST={DOMAIN}:8085 \\\n'
            'gcloud --project=obs-test pubsub subscriptions pull audit-logs-sub --auto-ack --limit=5'
        ),
    },
    "darktrace": {
        "name": "Darktrace",
        "auth_type": "HMAC-SHA1 (mock accepts any value)",
        "credentials": {"note": "Mock skips signature check — any Authorization header accepted"},
        "endpoints": [
            {"method": "GET", "path": "/modelbreaches",          "desc": "Model breaches"},
            {"method": "GET", "path": "/aianalyst/incident/log", "desc": "AI Analyst incidents"},
            {"method": "GET", "path": "/status",                 "desc": "System status"},
            {"method": "GET", "path": "/groups",                 "desc": "Device groups"},
        ],
        "curl": f'curl -s "{BASE}/modelbreaches?limit=5"',
    },
}

CONTAINERS = ["apigenie", "apigenie-nginx", "apigenie-kafka", "apigenie-zookeeper", "apigenie-pubsub"]

# ── HTML ──────────────────────────────────────────────────────────────────────

_LOGIN_HTML = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>API Genie · Admin Login</title>
<link rel="icon" type="image/png" href="/logo.png"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@500&display=swap" rel="stylesheet">
<style>
:root{
  --primary:#854EF3;--primary-deep:#7947D7;--primary-light:#A986FD;
  --surface:#ece6fa;--shadow-dark:rgba(105,70,184,.28);--shadow-light:rgba(255,255,255,.95);
  --text:#2a1d52;--text-soft:#5b4a8e;--text-mute:#8479ad;
}
*{box-sizing:border-box;margin:0;padding:0}
body{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;
  background:var(--surface);
  background-image:radial-gradient(circle at 12% 10%,rgba(169,134,253,.35),transparent 45%),
                   radial-gradient(circle at 88% 90%,rgba(133,78,243,.22),transparent 45%);
  background-attachment:fixed;
  font-family:"Inter",system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--text);
  -webkit-font-smoothing:antialiased;padding:32px 20px}
.brand{display:flex;align-items:center;gap:12px;margin-bottom:28px;text-decoration:none;color:var(--text)}
.brand-logo{width:56px;height:56px;border-radius:18px;background:var(--surface);
  box-shadow:7px 7px 14px var(--shadow-dark),-7px -7px 14px var(--shadow-light);
  display:grid;place-items:center;padding:6px}
.brand-logo img{width:100%;height:100%;object-fit:contain;mix-blend-mode:multiply}
.brand-name{font-size:1.15rem;font-weight:700;letter-spacing:-.01em;
  background:linear-gradient(135deg,var(--primary-deep),var(--primary),var(--primary-light));
  -webkit-background-clip:text;background-clip:text;color:transparent}
.brand-name small{display:block;font-size:.7rem;font-weight:500;color:var(--text-mute);
  letter-spacing:.06em;text-transform:uppercase;-webkit-text-fill-color:var(--text-mute)}
.card{background:var(--surface);border-radius:24px;padding:36px 32px;width:100%;max-width:400px;
  box-shadow:12px 12px 28px var(--shadow-dark),-12px -12px 28px var(--shadow-light)}
h1{font-size:1.4rem;font-weight:700;text-align:center;margin-bottom:6px;letter-spacing:-.01em;
  background:linear-gradient(135deg,var(--primary-deep),var(--primary) 50%,var(--primary-light));
  -webkit-background-clip:text;background-clip:text;color:transparent}
.sub{text-align:center;font-size:.88rem;color:var(--text-mute);margin-bottom:28px}
label{display:block;font-size:.78rem;font-weight:600;color:var(--text-soft);
  margin-bottom:8px;margin-top:18px;letter-spacing:.02em}
input{width:100%;background:var(--surface);border:none;border-radius:14px;padding:12px 16px;
  color:var(--text);font-family:inherit;font-size:.95rem;outline:none;transition:box-shadow .2s;
  box-shadow:inset 4px 4px 8px var(--shadow-dark),inset -4px -4px 8px var(--shadow-light)}
input:focus{box-shadow:inset 5px 5px 10px var(--shadow-dark),inset -5px -5px 10px var(--shadow-light),
  0 0 0 2px rgba(133,78,243,.25)}
button{width:100%;margin-top:28px;padding:13px;font-family:inherit;font-size:.98rem;font-weight:600;
  color:#fff;background:linear-gradient(135deg,var(--primary),var(--primary-deep));
  border:none;border-radius:14px;cursor:pointer;letter-spacing:.01em;
  box-shadow:6px 6px 14px var(--shadow-dark),-6px -6px 14px var(--shadow-light);
  transition:transform .15s,box-shadow .15s}
button:hover{transform:translateY(-1px);
  box-shadow:8px 8px 18px var(--shadow-dark),-8px -8px 18px var(--shadow-light),0 0 22px rgba(133,78,243,.35)}
button:active{transform:translateY(0);
  box-shadow:inset 4px 4px 8px rgba(105,70,184,.55),inset -4px -4px 8px rgba(255,255,255,.25)}
.err{color:#c0392b;background:rgba(192,57,43,.08);border-radius:10px;padding:10px 14px;
  font-size:.85rem;text-align:center;margin-top:14px}
footer{margin-top:32px;font-size:.85rem;color:var(--text-mute);text-align:center;letter-spacing:.02em}
footer .heart{display:inline-block;width:1em;height:1em;vertical-align:-0.15em;margin:0 .2em;
  color:var(--primary);animation:beat 1.6s ease-in-out infinite}
footer .brand-text{color:var(--primary-deep);font-weight:600}
@keyframes beat{0%,100%{transform:scale(1)}50%{transform:scale(1.18)}}
@media (prefers-reduced-motion:reduce){footer .heart{animation:none}}
</style>
</head>
<body>
<a class="brand" href="/" aria-label="Back to API Genie home">
  <span class="brand-logo"><img src="/logo.png" alt=""/></span>
  <span class="brand-name">API Genie<small>Admin Console</small></span>
</a>
<div class="card">
  <h1>Sign in</h1>
  <p class="sub">Restricted access · authorised operators only</p>
  <form method="post" action="/admin/login">
    <label for="u">Username</label>
    <input id="u" name="username" type="text" autocomplete="username" autofocus/>
    <label for="p">Password</label>
    <input id="p" name="password" type="password" autocomplete="current-password"/>
    <button type="submit">Continue</button>
    {error}
  </form>
</div>
<footer>
  Crafted with
  <svg class="heart" viewBox="0 0 24 24" fill="currentColor" aria-label="love" role="img">
    <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
  </svg>
  by the <span class="brand-text">RoarinPenguin</span>
</footer>
</body>
</html>"""

_DASH_HTML = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>ApiGenie · Admin</title>
<style>
:root{--deep:#10002b;--violet:#5a189a;--purple:#7b2cbf;--orchid:#9d4edd;--lilac:#c77dff;--mist:#e0aaff;--glow:rgba(199,125,255,.45);--sidebar:220px}
*{box-sizing:border-box;margin:0;padding:0}
body{display:flex;min-height:100vh;background:var(--deep);color:var(--mist);font-family:"Segoe UI",system-ui,sans-serif;font-size:.92rem}
/* Sidebar */
.sidebar{width:var(--sidebar);background:rgba(36,0,70,.8);border-right:1px solid rgba(199,125,255,.15);display:flex;flex-direction:column;padding:20px 0;flex-shrink:0;position:fixed;top:0;left:0;height:100vh;z-index:10}
.sidebar .brand{padding:0 20px 20px;font-size:1.1rem;font-weight:700;background:linear-gradient(90deg,#e0aaff,#c77dff);-webkit-background-clip:text;background-clip:text;color:transparent;border-bottom:1px solid rgba(199,125,255,.15)}
.nav-item{display:block;padding:11px 20px;color:rgba(224,170,255,.7);text-decoration:none;cursor:pointer;border-left:3px solid transparent;transition:all .15s}
.nav-item:hover,.nav-item.active{color:var(--mist);background:rgba(123,44,191,.2);border-left-color:var(--lilac)}
.nav-section{padding:16px 20px 6px;font-size:.72rem;color:rgba(224,170,255,.35);text-transform:uppercase;letter-spacing:.08em}
.sidebar .footer{margin-top:auto;padding:0 12px 12px;display:flex;flex-direction:column;gap:14px}
.logout a{display:block;padding:9px 14px;text-align:center;border-radius:10px;background:rgba(90,24,154,.3);color:rgba(224,170,255,.6);text-decoration:none;font-size:.85rem;transition:all .15s}
.logout a:hover{background:rgba(123,44,191,.4);color:var(--mist)}
.tagline{text-align:center;font-size:.72rem;color:rgba(224,170,255,.35);letter-spacing:.02em;line-height:1.5}
.tagline .heart{display:inline-block;width:.85em;height:.85em;vertical-align:-.1em;margin:0 .15em;color:#A986FD;animation:beat 1.6s ease-in-out infinite}
.tagline .brand-text{color:rgba(224,170,255,.6);font-weight:600}
@keyframes beat{0%,100%{transform:scale(1)}50%{transform:scale(1.18)}}
@media (prefers-reduced-motion:reduce){.tagline .heart{animation:none}}
/* Main */
.main{margin-left:var(--sidebar);flex:1;display:flex;flex-direction:column;min-height:100vh}
.topbar{padding:16px 24px;border-bottom:1px solid rgba(199,125,255,.1);display:flex;align-items:center;gap:12px;background:rgba(16,0,43,.6);backdrop-filter:blur(8px)}
.topbar h2{font-size:1rem;font-weight:600;color:var(--mist)}
.content{padding:24px;flex:1}
/* Cards */
.card{background:rgba(36,0,70,.55);border:1px solid rgba(199,125,255,.2);border-radius:14px;padding:20px;margin-bottom:16px}
.card-title{font-size:.82rem;font-weight:600;text-transform:uppercase;letter-spacing:.06em;color:var(--orchid);margin-bottom:14px}
/* Controls */
select{background:rgba(90,24,154,.25);border:1px solid rgba(199,125,255,.3);border-radius:8px;padding:7px 12px;color:var(--mist);font-size:.88rem;outline:none;cursor:pointer}
select:focus{border-color:var(--lilac)}
button,input[type=button]{background:linear-gradient(135deg,#7b2cbf,#9d4edd);border:none;border-radius:8px;padding:7px 16px;color:#fff;font-size:.85rem;font-weight:600;cursor:pointer;transition:filter .15s}
button:hover,input[type=button]:hover{filter:brightness(1.15)}
.btn-sm{padding:5px 12px;font-size:.8rem}
/* Requests table */
table{width:100%;border-collapse:collapse}
th{text-align:left;padding:8px 10px;font-size:.75rem;color:rgba(224,170,255,.5);text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid rgba(199,125,255,.12)}
td{padding:8px 10px;border-bottom:1px solid rgba(199,125,255,.07);vertical-align:top;word-break:break-all;max-width:240px}
tr:hover td{background:rgba(123,44,191,.1)}
.badge{display:inline-block;padding:2px 7px;border-radius:999px;font-size:.72rem;font-weight:600}
.b200{background:rgba(50,205,50,.15);color:#7fff7f}
.b4xx{background:rgba(255,140,0,.15);color:#ffb347}
.b5xx{background:rgba(255,50,50,.15);color:#ff7f7f}
.method{color:var(--lilac);font-weight:600;font-size:.78rem}
.ts{color:rgba(224,170,255,.45);font-size:.75rem}
.dur{color:rgba(224,170,255,.5);font-size:.75rem}
/* Detail expand */
details summary{cursor:pointer;color:var(--lilac);font-size:.78rem;padding:4px 0}
details pre{background:rgba(0,0,0,.3);border-radius:8px;padding:10px;font-size:.72rem;overflow-x:auto;margin-top:6px;max-height:220px;overflow-y:auto;color:rgba(224,170,255,.8)}
/* Log terminal */
.terminal{background:#000;border:1px solid rgba(199,125,255,.2);border-radius:10px;padding:14px;height:500px;overflow-y:auto;font-family:"JetBrains Mono","Fira Code",monospace;font-size:.75rem;line-height:1.6;color:#a8c0b0}
.terminal .err{color:#ff8080}
.terminal .warn{color:#ffd080}
/* Config */
.cfg-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:10px;margin-bottom:16px}
.cfg-item label{font-size:.72rem;color:rgba(224,170,255,.45);display:block;margin-bottom:3px}
.cfg-item code{font-family:monospace;font-size:.82rem;color:var(--mist);word-break:break-all}
.ep-list{list-style:none;margin-bottom:14px}
.ep-list li{display:flex;gap:10px;align-items:baseline;padding:5px 0;border-bottom:1px solid rgba(199,125,255,.08)}
.ep-method{min-width:42px;text-align:center;padding:1px 6px;border-radius:5px;font-size:.7rem;font-weight:700}
.GET{background:rgba(50,150,255,.2);color:#7fb5ff}
.POST{background:rgba(50,200,100,.2);color:#7fd6a0}
.ep-path{font-family:monospace;font-size:.8rem;color:var(--mist)}
.ep-desc{font-size:.75rem;color:rgba(224,170,255,.45);margin-left:auto}
.curl-block{position:relative}
.curl-block pre{background:rgba(0,0,0,.4);border:1px solid rgba(199,125,255,.2);border-radius:10px;padding:14px 14px 14px 14px;font-family:monospace;font-size:.78rem;color:#a8c0b0;overflow-x:auto;white-space:pre-wrap}
.copy-btn{position:absolute;top:8px;right:8px}
/* Tabs */
.tab-bar{display:flex;gap:4px;margin-bottom:20px}
.tab{padding:8px 18px;border-radius:8px;cursor:pointer;color:rgba(224,170,255,.55);font-size:.88rem;border:1px solid transparent;transition:all .15s}
.tab.active,.tab:hover{background:rgba(123,44,191,.3);color:var(--mist);border-color:rgba(199,125,255,.25)}
.tab.active{border-color:var(--lilac)}
.pane{display:none}.pane.active{display:block}
/* Misc */
.row{display:flex;align-items:center;gap:10px;margin-bottom:14px}
.empty{color:rgba(224,170,255,.3);font-style:italic;padding:20px 0;text-align:center}
.source-chips{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:16px}
.chip{padding:4px 12px;border-radius:999px;font-size:.75rem;border:1px solid rgba(199,125,255,.25);background:rgba(90,24,154,.2);color:rgba(224,170,255,.6);cursor:pointer;transition:all .15s}
.chip.active,.chip:hover{background:rgba(123,44,191,.4);color:var(--mist);border-color:var(--lilac)}
</style>
</head>
<body>

<nav class="sidebar">
  <div class="brand">⚙ ApiGenie Admin</div>
  <span class="nav-section">Monitor</span>
  <a class="nav-item active" onclick="showTab('requests', this)">📋 Requests</a>
  <a class="nav-item" onclick="showTab('logs', this)">📜 Container Logs</a>
  <span class="nav-section">Reference</span>
  <a class="nav-item" onclick="showTab('config', this)">🔧 Source Config</a>
  <span class="nav-section">System</span>
  <a class="nav-item" onclick="showTab('settings', this); loadSettings()">⚙ Settings</a>
  <div class="footer">
    <div class="logout"><a href="/admin/logout">Sign out</a></div>
    <div class="tagline">
      Crafted with
      <svg class="heart" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>
      by the<br/><span class="brand-text">RoarinPenguin</span>
    </div>
  </div>
</nav>

<div class="main">
  <div class="topbar"><h2 id="page-title">Request Inspector</h2></div>
  <div class="content">

    <!-- REQUESTS TAB -->
    <div class="pane active" id="pane-requests">
      <div class="card">
        <div class="card-title">Source</div>
        <div class="source-chips" id="source-chips"></div>
      </div>
      <div class="card">
        <div class="card-title" style="display:flex;justify-content:space-between;align-items:center">
          Recent calls <button class="btn-sm" onclick="loadRequests()">↺ Refresh</button>
        </div>
        <div id="req-table-wrap"><p class="empty">Select a source above</p></div>
      </div>
    </div>

    <!-- LOGS TAB -->
    <div class="pane" id="pane-logs">
      <div class="card">
        <div class="row">
          <select id="log-container">
            {container_options}
          </select>
          <button onclick="startLogs()">▶ Start</button>
          <button onclick="stopLogs()" style="background:rgba(90,24,154,.4);border:1px solid rgba(199,125,255,.3)">■ Stop</button>
          <button onclick="clearLog()" class="btn-sm" style="background:rgba(36,0,70,.6);border:1px solid rgba(199,125,255,.2)">Clear</button>
        </div>
        <div class="terminal" id="terminal">
          <span style="color:rgba(224,170,255,.3)">Select a container and click Start…</span>
        </div>
      </div>
    </div>

    <!-- CONFIG TAB -->
    <div class="pane" id="pane-config">
      <div class="card">
        <div class="card-title">Source</div>
        <div class="source-chips" id="cfg-chips"></div>
      </div>
      <div id="cfg-detail"><p class="empty">Select a source above</p></div>
    </div>

    <!-- SETTINGS TAB -->
    <div class="pane" id="pane-settings">
      <div class="card">
        <div class="card-title">Identity</div>
        <div class="cfg-grid" id="settings-identity"><p class="empty">Loading…</p></div>
        <p style="font-size:.78rem;color:rgba(224,170,255,.45);margin-top:8px">
          To change the public domain or Kafka advertised host, edit <code>.env</code>
          and run <code>docker compose up -d</code>. Kafka rewrites broker metadata at
          startup, so changing the advertised host requires a Kafka restart.
        </p>
      </div>

      <div class="card">
        <div class="card-title">TLS certificate</div>
        <div class="cfg-grid" id="settings-cert"><p class="empty">Loading…</p></div>
        <div class="row" style="margin-top:14px">
          <button onclick="showRenewCmd()" id="btn-renew">⚡ Renew certificate</button>
          <button class="btn-sm" onclick="loadSettings()" style="background:rgba(36,0,70,.6);border:1px solid rgba(199,125,255,.2)">↺ Refresh</button>
        </div>
        <pre id="renew-cmd" style="display:none;background:rgba(0,0,0,.4);border:1px solid rgba(199,125,255,.2);border-radius:8px;padding:12px;margin-top:12px;font-size:.78rem;color:#a8c0b0;white-space:pre-wrap"></pre>
      </div>

      <div class="card">
        <div class="card-title">Change admin password</div>
        <div class="row"><label style="min-width:140px;font-size:.82rem;color:rgba(224,170,255,.7)">Current password</label>
          <input id="pw-current" type="password" autocomplete="current-password" style="flex:1;background:rgba(90,24,154,.2);border:1px solid rgba(199,125,255,.35);border-radius:8px;padding:8px 12px;color:var(--mist);outline:none"/>
        </div>
        <div class="row"><label style="min-width:140px;font-size:.82rem;color:rgba(224,170,255,.7)">New password</label>
          <input id="pw-new" type="password" autocomplete="new-password" style="flex:1;background:rgba(90,24,154,.2);border:1px solid rgba(199,125,255,.35);border-radius:8px;padding:8px 12px;color:var(--mist);outline:none"/>
        </div>
        <div class="row"><label style="min-width:140px;font-size:.82rem;color:rgba(224,170,255,.7)">Confirm new</label>
          <input id="pw-confirm" type="password" autocomplete="new-password" style="flex:1;background:rgba(90,24,154,.2);border:1px solid rgba(199,125,255,.35);border-radius:8px;padding:8px 12px;color:var(--mist);outline:none"/>
        </div>
        <div class="row"><button onclick="changePassword()">Save</button>
          <span id="pw-msg" style="font-size:.85rem"></span>
        </div>
      </div>
    </div>

  </div>
</div>

<script>
const SOURCES = {sources_json};
let activeSource = null;
let activeTab = 'requests';
let logES = null;

// ── Tab navigation ────────────────────────────────────────────────────────────
function showTab(tab, el) {
  document.querySelectorAll('.pane').forEach(p => p.classList.remove('active'));
  document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));
  document.getElementById('pane-' + tab).classList.add('active');
  if (el) el.classList.add('active');
  activeTab = tab;
  const titles = {requests:'Request Inspector', logs:'Container Logs', config:'Source Config', settings:'Settings'};
  document.getElementById('page-title').textContent = titles[tab];
}

// ── Source chips ──────────────────────────────────────────────────────────────
function buildChips(containerId, onClick) {
  const wrap = document.getElementById(containerId);
  wrap.innerHTML = '';
  Object.entries(SOURCES).forEach(([id, src]) => {
    const c = document.createElement('span');
    c.className = 'chip';
    c.textContent = src.name;
    c.dataset.id = id;
    c.onclick = () => {
      wrap.querySelectorAll('.chip').forEach(x => x.classList.remove('active'));
      c.classList.add('active');
      onClick(id);
    };
    wrap.appendChild(c);
  });
}

// ── Requests ──────────────────────────────────────────────────────────────────
function selectSource(id) {
  activeSource = id;
  // sync chips in both tabs if somehow both are rendered
  document.querySelectorAll('[data-id="' + id + '"]').forEach(c => c.classList.add('active'));
  loadRequests();
}

async function loadRequests() {
  if (!activeSource) return;
  const wrap = document.getElementById('req-table-wrap');
  wrap.innerHTML = '<p class="empty">Loading…</p>';
  try {
    const r = await fetch('/admin/api/requests/' + activeSource);
    if (!r.ok) { wrap.innerHTML = '<p class="empty">Error: ' + r.status + ' ' + r.statusText + ' — try signing in again.</p>'; return; }
    const data = await r.json();
    if (!data.length) { wrap.innerHTML = '<p class="empty">No requests recorded yet — wait for the collector to call in.</p>'; return; }
    let html = `<table><thead><tr>
      <th>Time</th><th>Method</th><th>Path</th><th>Status</th><th>ms</th><th>Client</th><th>Detail</th>
    </tr></thead><tbody>`;
    data.forEach((e, i) => {
      const bc = e.status < 300 ? 'b200' : e.status < 500 ? 'b4xx' : 'b5xx';
      const q = e.query ? '?' + e.query : '';
      const hdr = JSON.stringify(e.req_headers, null, 2);
      const body = e.req_body || '';
      html += `<tr>
        <td class="ts">${e.ts.replace('T',' ')}</td>
        <td class="method">${e.method}</td>
        <td style="font-family:monospace;font-size:.78rem">${e.path}${q}</td>
        <td><span class="badge ${bc}">${e.status}</span></td>
        <td class="dur">${e.duration_ms}</td>
        <td class="ts">${e.client}</td>
        <td><details><summary>headers${body ? ' + body' : ''}</summary>
          <pre>${escHtml(hdr)}${body ? '\\n\\n--- Body ---\\n' + escHtml(body.substring(0,800)) : ''}</pre>
        </details></td>
      </tr>`;
    });
    html += '</tbody></table>';
    wrap.innerHTML = html;
  } catch(err) { wrap.innerHTML = '<p class="empty">Error: ' + err + '</p>'; }
}

// ── Logs ──────────────────────────────────────────────────────────────────────
function startLogs() {
  stopLogs();
  const container = document.getElementById('log-container').value;
  const term = document.getElementById('terminal');
  term.innerHTML = '<span style="color:var(--orchid)">Connecting to ' + container + '…</span>\\n';
  logES = new EventSource('/admin/api/logs/' + container);
  logES.onmessage = (e) => {
    const line = JSON.parse(e.data);
    const span = document.createElement('span');
    span.className = line.includes('ERROR') || line.includes('error') ? 'err'
                   : line.includes('WARN')  || line.includes('warn')  ? 'warn' : '';
    span.textContent = line + '\\n';
    term.appendChild(span);
    term.scrollTop = term.scrollHeight;
    // keep DOM lean
    while (term.childNodes.length > 600) term.removeChild(term.firstChild);
  };
  logES.onerror = () => { term.innerHTML += '<span class="err">Connection closed.\\n</span>'; stopLogs(); };
}

function stopLogs() { if (logES) { logES.close(); logES = null; } }
function clearLog() { document.getElementById('terminal').innerHTML = ''; }

// ── Config ────────────────────────────────────────────────────────────────────
function showConfig(id) {
  const src = SOURCES[id];
  const wrap = document.getElementById('cfg-detail');

  const creds = Object.entries(src.credentials || {}).map(([k,v]) =>
    `<div class="cfg-item"><label>${k}</label><code>${escHtml(v)}</code></div>`
  ).join('');

  const eps = (src.endpoints || []).map(ep =>
    `<li>
      <span class="ep-method ${ep.method}">${ep.method}</span>
      <span class="ep-path">${escHtml(ep.path)}</span>
      <span class="ep-desc">${ep.desc}</span>
    </li>`
  ).join('');

  const curl = src.curl || '';

  wrap.innerHTML = `
    <div class="card">
      <div class="card-title">${src.name}</div>
      <p style="font-size:.82rem;color:rgba(224,170,255,.55);margin-bottom:14px">Auth: ${src.auth_type}</p>
      <div class="card-title" style="font-size:.72rem">Credentials</div>
      <div class="cfg-grid">${creds}</div>
      <div class="card-title" style="font-size:.72rem">Endpoints</div>
      <ul class="ep-list">${eps}</ul>
      <div class="card-title" style="font-size:.72rem">Test with curl</div>
      <div class="curl-block">
        <pre id="curl-pre">${escHtml(curl)}</pre>
        <button class="btn-sm copy-btn" onclick="copyCurl()">Copy</button>
      </div>
    </div>`;
}

function copyCurl() {
  const text = document.getElementById('curl-pre').textContent;
  navigator.clipboard.writeText(text).then(() => {
    const btn = document.querySelector('.copy-btn');
    btn.textContent = 'Copied!';
    setTimeout(() => btn.textContent = 'Copy', 2000);
  });
}

function escHtml(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

// ── Settings tab ─────────────────────────────────────────────────────────
async function loadSettings() {
  // Identity
  try {
    const r = await fetch('/admin/api/settings');
    if (!r.ok) throw new Error(r.status);
    const s = await r.json();
    const items = [
      ['Public domain',         s.domain],
      ['Kafka advertised host', s.kafka_advertised_host],
      ['TLS mode',              s.tls_mode],
      ['Admin username',        s.admin_username],
      ['Password source',       s.password_source],
    ].map(([k,v]) => `<div class="cfg-item"><label>${k}</label><code>${escHtml(v)}</code></div>`).join('');
    document.getElementById('settings-identity').innerHTML = items;
  } catch(e) {
    document.getElementById('settings-identity').innerHTML = '<p class="empty">Error loading: ' + e + '</p>';
  }
  // Cert
  try {
    const r = await fetch('/admin/api/cert');
    const c = await r.json();
    if (c.error) {
      document.getElementById('settings-cert').innerHTML = '<p class="empty">' + escHtml(c.error) + '</p>';
      return;
    }
    const days = c.days_remaining;
    const dayColor = days < 0 ? '#ff7f7f' : days < 14 ? '#ffb347' : days < 30 ? '#e0aaff' : '#7fff7f';
    const items = [
      ['Subject',         c.subject],
      ['Issuer',          c.issuer],
      ['Serial',          c.serial],
      ['Subject Alt Names', c.san],
      ['Not before',      c.not_before],
      ['Not after',       c.not_after],
      ['Days remaining',  `<span style="color:${dayColor};font-weight:600">${days}</span>`],
      ['Self-signed',     c.self_signed ? 'yes' : 'no'],
    ].map(([k,v]) => `<div class="cfg-item"><label>${k}</label><code>${v}</code></div>`).join('');
    document.getElementById('settings-cert').innerHTML = items;
  } catch(e) {
    document.getElementById('settings-cert').innerHTML = '<p class="empty">Error loading cert: ' + e + '</p>';
  }
}

async function showRenewCmd() {
  const r = await fetch('/admin/api/cert/renew-command');
  const j = await r.json();
  const pre = document.getElementById('renew-cmd');
  pre.style.display = 'block';
  pre.textContent = j.note + '\n\n' + j.command;
}

async function changePassword() {
  const cur = document.getElementById('pw-current').value;
  const nw  = document.getElementById('pw-new').value;
  const cf  = document.getElementById('pw-confirm').value;
  const msg = document.getElementById('pw-msg');
  msg.style.color = '#ff7f7f';
  if (!cur || !nw) { msg.textContent = 'Fill all fields.'; return; }
  if (nw !== cf) { msg.textContent = 'New passwords do not match.'; return; }
  if (nw.length < 8) { msg.textContent = 'New password must be at least 8 characters.'; return; }
  msg.style.color = 'rgba(224,170,255,.6)';
  msg.textContent = 'Saving…';
  try {
    const fd = new FormData();
    fd.set('current', cur); fd.set('new', nw);
    const r = await fetch('/admin/api/change-password', { method:'POST', body: fd });
    const j = await r.json();
    if (!r.ok) { msg.style.color = '#ff7f7f'; msg.textContent = j.error || ('Error ' + r.status); return; }
    msg.style.color = '#7fff7f';
    msg.textContent = 'Password updated. Existing sessions remain valid.';
    document.getElementById('pw-current').value = '';
    document.getElementById('pw-new').value = '';
    document.getElementById('pw-confirm').value = '';
    loadSettings();
  } catch(e) {
    msg.style.color = '#ff7f7f';
    msg.textContent = 'Error: ' + e;
  }
}

// ── Init ──────────────────────────────────────────────────────────────────────
buildChips('source-chips', selectSource);
buildChips('cfg-chips', showConfig);
// auto-select first source
document.querySelector('#source-chips .chip')?.click();
</script>
</body>
</html>"""


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/login", response_class=HTMLResponse)
async def login_page():
    return HTMLResponse(_LOGIN_HTML.replace("{error}", ""))


@router.post("/login")
async def login_submit(username: str = Form(...), password: str = Form(...)):
    user_ok = hmac.compare_digest(username, ADMIN_USER)
    pass_ok = _check_password(password)
    if user_ok and pass_ok:
        tok = _new_session()
        resp = RedirectResponse("/admin/", status_code=303)
        resp.set_cookie(COOKIE, tok, httponly=True, samesite="lax", max_age=SESSION_TTL)
        return resp
    html = _LOGIN_HTML.replace("{error}", '<p class="err">Invalid credentials.</p>')
    return HTMLResponse(html, status_code=401)


@router.get("/logout")
async def logout(ag_session: str | None = Cookie(None)):
    _sessions.pop(ag_session or "", None)
    resp = RedirectResponse("/admin/login", status_code=303)
    resp.delete_cookie(COOKIE)
    return resp


@router.get("/", response_class=HTMLResponse)
@router.get("", response_class=HTMLResponse)
async def dashboard(ag_session: str | None = Cookie(None)):
    if not _valid(ag_session):
        return RedirectResponse("/admin/login", status_code=303)

    opts = "\n".join(f'<option value="{c}">{c}</option>' for c in CONTAINERS)
    sources_json = json.dumps({k: {
        "name": v["name"],
        "auth_type": v["auth_type"],
        "credentials": {str(ck): str(cv) for ck, cv in v.get("credentials", {}).items()},
        "endpoints": v.get("endpoints", []),
        "curl": v.get("curl", ""),
    } for k, v in SOURCES.items()})

    html = _DASH_HTML.replace("{container_options}", opts).replace("{sources_json}", sources_json)
    return HTMLResponse(html)


# Lazy, per-process disposable RSA key for the dummy GCP SA JSON.
# Generated on first request and held in memory only — never persisted, so no
# credential-shaped blob lives at rest in the repo or on disk.
_DUMMY_SA_PEM: str | None = None


def _dummy_sa_pem() -> str:
    global _DUMMY_SA_PEM
    if _DUMMY_SA_PEM is None:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import rsa

        key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
        pem_bytes = key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
        _DUMMY_SA_PEM = pem_bytes.decode("ascii")
    return _DUMMY_SA_PEM


@router.get("/gcp-sa.json")
async def gcp_dummy_sa(ag_session: str | None = Cookie(None)):
    """Generate a dummy GCP service-account JSON for the Pub/Sub emulator.

    Observo's GCP source actually loads the private_key with OpenSSL and signs
    JWTs with it before realising the endpoint is the emulator, so the key has
    to be a real RSA-2048 PEM. We generate one disposable key per process,
    keep it in memory only, and never write it to disk. The collector still
    talks to the emulator — no real GCP traffic happens.
    """
    if not _valid(ag_session):
        return RedirectResponse("/admin/login", status_code=303)

    pem_escaped = _dummy_sa_pem().replace("\n", "\\n")
    payload = json.dumps({
        "type": "service_account",
        "project_id": "obs-test",
        "private_key_id": "0" * 40,
        # Embed the PEM with literal \n escapes (real Google JSON shape).
        "__pem_placeholder__": "ENCODED_BELOW",
        "client_email": "apigenie-emulator@obs-test.iam.gserviceaccount.com",
        "client_id": "1" + "0" * 20,
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        # token_uri intentionally points at OUR fake OAuth endpoint so
        # collectors that do not honour PUBSUB_EMULATOR_HOST never call real
        # Google (which would reject the unknown service account).
        "token_uri": f"https://{DOMAIN}/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/apigenie-emulator%40obs-test.iam.gserviceaccount.com",
        "universe_domain": "googleapis.com",
    }, indent=2)
    # Splice the real private_key field into the rendered JSON (avoids
    # double-escaping the embedded PEM when serialising via json.dumps).
    payload = payload.replace(
        '"__pem_placeholder__": "ENCODED_BELOW",',
        f'"private_key": "{pem_escaped}",',
    )
    return Response(
        content=payload,
        media_type="application/json",
        headers={"Content-Disposition": 'attachment; filename="apigenie-pubsub-sa.json"'},
    )


@router.get("/api/requests/{source}")
async def api_requests(source: str, ag_session: str | None = Cookie(None)):
    if not _valid(ag_session):
        return JSONResponse({"error": "unauthorized"}, status_code=401)
    data = list(REQUEST_TRACE.get(source, []))
    return JSONResponse(data)


@router.get("/api/logs/{container}")
async def api_logs(container: str, ag_session: str | None = Cookie(None)):
    if not _valid(ag_session):
        return JSONResponse({"error": "unauthorized"}, status_code=401)
    # Sanitise container name
    allowed = set(CONTAINERS)
    if container not in allowed:
        return JSONResponse({"error": "unknown container"}, status_code=400)

    async def generate():
        try:
            proc = await asyncio.create_subprocess_exec(
                "docker", "logs", "--tail=200", "--follow", "--timestamps", container,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,
            )
            assert proc.stdout
            while True:
                try:
                    line = await asyncio.wait_for(proc.stdout.readline(), timeout=30)
                except asyncio.TimeoutError:
                    yield "data: \"[heartbeat]\"\n\n"
                    continue
                if not line:
                    break
                yield f"data: {json.dumps(line.decode('utf-8', errors='replace').rstrip())}\n\n"
        except Exception as exc:
            yield f"data: {json.dumps('[error: ' + str(exc) + ']')}\n\n"

    return StreamingResponse(generate(), media_type="text/event-stream",
                              headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


# ── Settings tab API ──────────────────────────────────────────────────────────

CERT_DIR = Path(os.environ.get("APIGENIE_CERT_DIR", f"/certs/{DOMAIN}"))


def _password_source() -> str:
    """Tell the UI where the active password is coming from."""
    if ADMIN_PASSWORD_FILE.is_file():
        return f"override file ({ADMIN_PASSWORD_FILE})"
    if ADMIN_HASH:
        return "ADMIN_PASSWORD_HASH env var"
    if ADMIN_PASS:
        return "ADMIN_PASSWORD plaintext (insecure — set a hash)"
    return "none configured (login disabled)"


@router.get("/api/settings")
async def api_settings(ag_session: str | None = Cookie(None)):
    if not _valid(ag_session):
        return JSONResponse({"error": "unauthorized"}, status_code=401)
    return JSONResponse({
        "domain": DOMAIN,
        "kafka_advertised_host": KAFKA_HOST,
        "tls_mode": TLS_MODE,
        "admin_username": ADMIN_USER,
        "password_source": _password_source(),
    })


@router.get("/api/cert")
async def api_cert(ag_session: str | None = Cookie(None)):
    if not _valid(ag_session):
        return JSONResponse({"error": "unauthorized"}, status_code=401)

    cert_path = CERT_DIR / "fullchain.pem"
    if not cert_path.is_file():
        return JSONResponse({"error": f"Certificate not found at {cert_path}. "
                                       "Run scripts/bootstrap.sh on the host or place "
                                       "your own fullchain.pem there."}, status_code=200)
    try:
        from cryptography import x509
        from cryptography.x509.oid import ExtensionOID, NameOID
        from datetime import datetime, timezone

        data = cert_path.read_bytes()
        cert = x509.load_pem_x509_certificate(data)

        def _name_str(name) -> str:
            return ", ".join(f"{a.oid._name}={a.value}" for a in name)

        try:
            san_ext = cert.extensions.get_extension_for_oid(ExtensionOID.SUBJECT_ALTERNATIVE_NAME)
            san_parts = []
            for entry in san_ext.value:
                cls = type(entry).__name__
                prefix = "DNS" if cls == "DNSName" else "IP" if cls == "IPAddress" else cls
                san_parts.append(f"{prefix}:{entry.value}")
            san = ", ".join(san_parts) if san_parts else "(none)"
        except x509.ExtensionNotFound:
            san = "(none)"

        not_before = cert.not_valid_before_utc
        not_after  = cert.not_valid_after_utc
        days_remaining = int((not_after - datetime.now(timezone.utc)).total_seconds() // 86400)

        subject = _name_str(cert.subject)
        issuer  = _name_str(cert.issuer)
        self_signed = subject == issuer

        return JSONResponse({
            "subject": subject,
            "issuer":  issuer,
            "serial":  format(cert.serial_number, "x"),
            "san":     san,
            "not_before": not_before.strftime("%Y-%m-%d %H:%M UTC"),
            "not_after":  not_after.strftime("%Y-%m-%d %H:%M UTC"),
            "days_remaining": days_remaining,
            "self_signed": self_signed,
        })
    except Exception as exc:
        return JSONResponse({"error": f"Failed to parse {cert_path}: {exc}"}, status_code=200)


@router.get("/api/cert/renew-command")
async def api_cert_renew_command(ag_session: str | None = Cookie(None)):
    """Return the shell command the operator should run on the host to renew.

    We deliberately don't auto-execute: the certbot run needs HTTP-01 reachable
    on port 80 and produces output the operator should see directly. Auto-exec
    inside this container would also need bind-mounted host paths that we can't
    portably resolve from inside the container.
    """
    if not _valid(ag_session):
        return JSONResponse({"error": "unauthorized"}, status_code=401)

    if TLS_MODE == "letsencrypt":
        cmd = ("docker compose --profile letsencrypt run --rm certbot && \\\n"
               "  docker compose restart nginx kafka-cert-init kafka")
        note = ("Run this from the repository root on the Docker host. "
                "Requires DNS for the domain to point at this host and port 80 reachable.")
    elif TLS_MODE == "self-signed":
        cmd = (f"./scripts/gen-self-signed.sh {DOMAIN} && \\\n"
               "  docker compose restart nginx kafka-cert-init kafka")
        note = ("Self-signed cert mode. Re-running the generator produces a fresh "
                "825-day cert; restart nginx + kafka to pick it up.")
    else:
        cmd = ("# TLS_MODE=provided — replace these files manually:\n"
               f"#   {CERT_DIR}/fullchain.pem\n"
               f"#   {CERT_DIR}/privkey.pem\n"
               "docker compose restart nginx kafka-cert-init kafka")
        note = "TLS mode is 'provided'. Replace the files yourself, then restart."

    return JSONResponse({"command": cmd, "note": note, "tls_mode": TLS_MODE})


@router.post("/api/change-password")
async def api_change_password(
    current: str = Form(...),
    new:     str = Form(...),
    ag_session: str | None = Cookie(None),
):
    if not _valid(ag_session):
        return JSONResponse({"error": "unauthorized"}, status_code=401)
    if not _check_password(current):
        return JSONResponse({"error": "Current password is incorrect."}, status_code=400)
    if len(new) < 8:
        return JSONResponse({"error": "New password must be at least 8 characters."}, status_code=400)

    new_hash = _hash_password(new)
    try:
        ADMIN_PASSWORD_FILE.parent.mkdir(parents=True, exist_ok=True)
        # Atomic write: rename over the target so a crash mid-write can't leave
        # a half-written file that locks out logins.
        tmp = ADMIN_PASSWORD_FILE.with_suffix(".tmp")
        tmp.write_text(new_hash + "\n", encoding="utf-8")
        tmp.chmod(0o600)
        tmp.replace(ADMIN_PASSWORD_FILE)
    except OSError as exc:
        return JSONResponse({"error": f"Could not persist new hash: {exc}"}, status_code=500)

    return JSONResponse({"ok": True})
