"""Tests for persona splicing into temp detection rules (v5.3 Step 1, Layer 3).

When the scenario engine builds a temporary detection rule for a
phase it must enrich ``field_overrides`` with the persona-projected
values for that source so the events the rule injects carry the
scenario's victim / attacker / host / payload identifiers instead of
fresh random ones generated by ``sources/*.py``.

Contract enforced here:

* ``attack_scenarios._splice_persona_overrides(phase, scenario)``
  returns a NEW dict that is ``phase['field_overrides']`` plus every
  ``event_field ⇒ persona_value`` pair the source's
  ``PERSONA_PROJECTION`` resolves against the scenario's
  ``personas`` bundle.
* The phase's explicit ``field_overrides`` win over the persona
  projection for the same key — the operator's hand-written override
  is the authority of last resort. (Test: phase overrides
  ``actor.alternateId`` to a literal — splice MUST leave it
  untouched.)
* If a slot is missing or empty in the persona bundle, the
  corresponding event field is skipped (no empty string on the
  wire, no KeyError).
* If the scenario has no ``personas`` key (legacy record) the
  splicer is a no-op — backward compatibility for in-flight
  scenarios saved before v5.3.
* Source ids accept both canonical and UI-alias forms
  (``entra_id`` ↔ ``azure_ad``) — splice MUST resolve via
  ``sources.get_persona_projection``.
* ``_create_temp_rule`` actually calls the splicer: the saved
  detection rule's ``field_overrides`` reflect the bundle.
"""
from __future__ import annotations

from unittest.mock import patch


# ── Pure splice unit ────────────────────────────────────────────────


def test_splice_adds_projected_persona_fields_to_overrides():
    """Given an Okta phase and a populated persona bundle, the
    spliced overrides must include actor.alternateId/displayName +
    client.ipAddress sourced from the bundle, alongside whatever
    the phase had configured."""
    import attack_scenarios

    phase = {"source": "okta",
             "field_overrides": {"outcome.result": "FAILURE",
                                 "displayMessage": "Brute force"}}
    scenario = {
        "personas": {
            "victim_user": {"email": "alice@acme.test", "name": "Alice",
                            "username": "alice", "upn": "alice@acme.test",
                            "object_id": "u-1"},
            "victim_host": {"hostname": "ALICE-PC", "ip": "10.0.0.5",
                            "os": "Windows 11", "agent_uuid": "h-1"},
            "attacker":    {"ip": "185.220.101.42", "country": "RU",
                            "email": "x@bad.test", "domain": "bad.test",
                            "asn": "AS9009"},
            "malicious":   {"file_name": "x.docm", "sha256": "a"*64,
                            "md5": "b"*32, "process": "WINWORD.EXE",
                            "cmd_line": "winword.exe"},
        }
    }

    out = attack_scenarios._splice_persona_overrides(phase, scenario)

    # Operator-set fields are preserved.
    assert out["outcome.result"]   == "FAILURE"
    assert out["displayMessage"]   == "Brute force"
    # Persona-projected fields stamped onto the rule.
    assert out["actor.alternateId"] == "alice@acme.test"
    assert out["actor.displayName"] == "Alice"
    assert out["client.ipAddress"]  == "185.220.101.42"
    # Returned dict is NEW — splice must not mutate the phase.
    assert "actor.alternateId" not in phase["field_overrides"]


def test_splice_does_not_clobber_phase_authored_overrides():
    """Operator-authored ``field_overrides`` win. A phase that
    explicitly overrides ``actor.alternateId`` (e.g. to a specific
    breached account) MUST keep that value — persona splicing only
    fills gaps."""
    import attack_scenarios

    phase = {"source": "okta",
             "field_overrides": {"actor.alternateId": "ceo@acme.test"}}
    scenario = {"personas": {
        "victim_user": {"email": "alice@acme.test", "name": "Alice",
                        "username": "alice", "upn": "alice@acme.test",
                        "object_id": "u-1"},
        "victim_host": {"hostname": "X", "ip": "10.0.0.1", "os": "W",
                        "agent_uuid": "a"},
        "attacker":    {"ip": "1.2.3.4", "country": "RU",
                        "email": "x@bad.test", "domain": "bad.test",
                        "asn": "AS1"},
        "malicious":   {"file_name": "f", "sha256": "a"*64, "md5": "b"*32,
                        "process": "p", "cmd_line": "c"},
    }}
    out = attack_scenarios._splice_persona_overrides(phase, scenario)
    assert out["actor.alternateId"] == "ceo@acme.test", (
        "phase-authored override must win over persona splice")


def test_splice_skips_empty_or_missing_persona_slots():
    """An empty string on the bundle ⇒ skip the projection for that
    field, never stamp an empty value on the wire."""
    import attack_scenarios

    phase = {"source": "okta", "field_overrides": {}}
    scenario = {"personas": {
        "victim_user": {"email": "alice@acme.test", "name": "",
                        "username": "alice", "upn": "alice@acme.test",
                        "object_id": "u"},
        "victim_host": {"hostname": "H", "ip": "10.0.0.1", "os": "W",
                        "agent_uuid": "a"},
        "attacker":    {"ip": "", "country": "RU", "email": "x@bad.test",
                        "domain": "bad.test", "asn": "AS1"},
        "malicious":   {"file_name": "f", "sha256": "a"*64, "md5": "b"*32,
                        "process": "p", "cmd_line": "c"},
    }}
    out = attack_scenarios._splice_persona_overrides(phase, scenario)
    assert out["actor.alternateId"] == "alice@acme.test"
    # Empty bundle values are NOT stamped.
    assert "actor.displayName" not in out
    assert "client.ipAddress"  not in out


def test_splice_is_noop_when_scenario_has_no_personas():
    """Legacy scenarios saved before v5.3 carry no ``personas`` key.
    The splicer must return the phase's overrides untouched and not
    raise."""
    import attack_scenarios

    phase = {"source": "okta",
             "field_overrides": {"outcome.result": "FAILURE"}}
    out = attack_scenarios._splice_persona_overrides(phase, {})
    assert out == {"outcome.result": "FAILURE"}
    # Caller is allowed to use the result freely — must not be the
    # same identity as phase['field_overrides'] (would let the caller
    # mutate the persisted phase by accident).
    assert out is not phase["field_overrides"]


def test_splice_resolves_source_aliases():
    """A phase declared on the bindings-UI alias ``entra_id`` must
    pick up the ``azure_ad`` projection. Without alias resolution
    the splicer would silently no-op every Entra ID phase."""
    import attack_scenarios

    phase = {"source": "entra_id",
             "field_overrides": {}}
    scenario = {"personas": {
        "victim_user": {"email": "alice@acme.test", "name": "Alice",
                        "username": "alice", "upn": "alice@acme.test",
                        "object_id": "u"},
        "victim_host": {"hostname": "H", "ip": "10.0.0.1", "os": "W",
                        "agent_uuid": "a"},
        "attacker":    {"ip": "1.2.3.4", "country": "RU",
                        "email": "x@bad.test", "domain": "bad.test",
                        "asn": "AS1"},
        "malicious":   {"file_name": "f", "sha256": "a"*64, "md5": "b"*32,
                        "process": "p", "cmd_line": "c"},
    }}
    out = attack_scenarios._splice_persona_overrides(phase, scenario)
    assert out["userPrincipalName"] == "alice@acme.test"
    assert out["ipAddress"]         == "1.2.3.4"


def test_splice_is_noop_for_unknown_source():
    """A phase on a source without a PERSONA_PROJECTION (e.g.
    ``darktrace`` in v5.3 phase 1) must still execute — the splicer
    returns the phase's overrides unchanged. The scenario keeps
    running, just without cross-source correlation on that one source."""
    import attack_scenarios

    phase = {"source": "darktrace", "field_overrides": {"x": 1}}
    scenario = {"personas": {
        "victim_user": {"email": "alice@acme.test", "name": "A",
                        "username": "a", "upn": "alice@acme.test",
                        "object_id": "u"},
        "victim_host": {"hostname": "H", "ip": "10.0.0.1", "os": "W",
                        "agent_uuid": "a"},
        "attacker":    {"ip": "1.2.3.4", "country": "RU",
                        "email": "x@bad.test", "domain": "bad.test",
                        "asn": "AS1"},
        "malicious":   {"file_name": "f", "sha256": "a"*64, "md5": "b"*32,
                        "process": "p", "cmd_line": "c"},
    }}
    out = attack_scenarios._splice_persona_overrides(phase, scenario)
    assert out == {"x": 1}


# ── Integration: _create_temp_rule actually splices ────────────────


def test_create_temp_rule_persists_persona_overrides(tmp_path,
                                                       monkeypatch):
    """The rule saved by ``_create_temp_rule`` MUST carry the spliced
    persona fields on its ``field_overrides``. This is the
    end-to-end contract that downstream injection in
    ``detection_rules.inject_detection_events`` relies on."""
    import attack_scenarios
    import detection_rules

    phase = {
        "phase_id": "p1",
        "name":     "Phishing email",
        "source":   "okta",
        "periodicity": 5,
        "field_overrides": {"outcome.result": "FAILURE"},
        "time_offset_pct": 0,
    }
    scenario = {
        "id": "scen-1",
        "personas": {
            "victim_user": {"email": "bob@acme.test", "name": "Bob",
                            "username": "bob", "upn": "bob@acme.test",
                            "object_id": "u-1"},
            "victim_host": {"hostname": "BOB-PC", "ip": "10.0.0.5",
                            "os": "Windows 11", "agent_uuid": "h-1"},
            "attacker":    {"ip": "203.0.113.66", "country": "IR",
                            "email": "z@evil.test", "domain": "evil.test",
                            "asn": "AS31549"},
            "malicious":   {"file_name": "x", "sha256": "a"*64,
                            "md5": "b"*32, "process": "p", "cmd_line": "c"},
        },
    }

    # Make _create_temp_rule see this scenario when it asks for it.
    with patch.object(attack_scenarios, "_load_scenarios",
                       return_value=[scenario]):
        rid = attack_scenarios._create_temp_rule(
            phase, attack_id="atk-1", scenario_id="scen-1",
            total_seconds=60, phase_start=0,
        )
    assert rid, "rule must be created"

    saved = detection_rules.get_rule(rid)
    assert saved is not None
    ov = saved["field_overrides"]
    # Phase override preserved
    assert ov["outcome.result"]   == "FAILURE"
    # Persona splice applied
    assert ov["actor.alternateId"] == "bob@acme.test"
    assert ov["client.ipAddress"]  == "203.0.113.66"
    # Scenario / attack metadata still stamped (unrelated to persona
    # but lives on the same dict — guard against accidental wipe).
    assert ov["phase.id"]          == "p1"
    assert ov["attack.id"]         == "atk-1"


# ── v5.1.8: Proofpoint policyRoutes tagging ────────────────────────


def test_create_temp_rule_proofpoint_tags_policyroutes(monkeypatch):
    """Proofpoint scenario rules MUST append ``apigenie-attack:<id>`` and
    ``apigenie-phase:<id>`` tokens to ``policyRoutes`` in addition to
    the plain ``attack.id`` / ``phase.id`` dotted overrides.

    Rationale: S1's Proofpoint TAP parser does not surface unknown
    top-level fields under ``unmapped.*`` the way the M365 and Okta
    parsers do — sending only ``attack.id`` at top level produces
    correctly stamped wire events that arrive in the data lake
    stripped. The ``policyRoutes`` String array is Proofpoint-native
    and every SIEM ingestor preserves it verbatim, so operators get
    a deterministic way to filter scenario events by attack_id.
    """
    import attack_scenarios
    import detection_rules

    phase = {
        "phase_id": "pp-phase",
        "name":     "Proofpoint Initial Access",
        "source":   "proofpoint",
        "periodicity": 3,
        "field_overrides": {},
        "time_offset_pct": 0,
    }
    scenario = {
        "id": "scen-pp",
        "personas": {
            "victim_user": {"email": "victim@test.test", "name": "V",
                            "username": "v", "upn": "victim@test.test",
                            "object_id": "u"},
            "attacker":    {"ip": "203.0.113.7", "country": "US",
                            "email": "atk@evil.test", "domain": "evil.test",
                            "asn": "AS0"},
        },
    }

    with patch.object(attack_scenarios, "_load_scenarios",
                       return_value=[scenario]):
        rid = attack_scenarios._create_temp_rule(
            phase, attack_id="atk-pp-1", scenario_id="scen-pp",
            total_seconds=60, phase_start=0,
        )
    assert rid
    saved = detection_rules.get_rule(rid)
    assert saved is not None
    ov = saved["field_overrides"]

    # The two plain overrides remain — every other parser uses them.
    assert ov["attack.id"] == "atk-pp-1"
    assert ov["phase.id"]  == "pp-phase"
    # Persona splice still works.
    assert ov["headerTo"]  == "victim@test.test"
    assert ov["sender"]    == "atk@evil.test"

    # And the new Proofpoint-specific belt-and-braces tagging.
    routes = ov.get("policyRoutes")
    assert isinstance(routes, list) and len(routes) >= 3
    assert "default_inbound" in routes
    assert "apigenie-attack:atk-pp-1" in routes
    assert "apigenie-phase:pp-phase" in routes


def test_create_temp_rule_non_proofpoint_does_not_touch_policyroutes(monkeypatch):
    """Non-Proofpoint phases MUST NOT receive ``policyRoutes`` in their
    overrides — the field is meaningless outside of Proofpoint and would
    confuse other parsers if leaked across sources."""
    import attack_scenarios
    import detection_rules

    phase = {
        "phase_id": "m365-phase",
        "name":     "M365 Collection",
        "source":   "m365",
        "periodicity": 4,
        "field_overrides": {},
        "time_offset_pct": 0,
    }
    scenario = {"id": "scen-m", "personas": {}}
    with patch.object(attack_scenarios, "_load_scenarios",
                       return_value=[scenario]):
        rid = attack_scenarios._create_temp_rule(
            phase, attack_id="atk-m-1", scenario_id="scen-m",
            total_seconds=60, phase_start=0,
        )
    assert rid
    saved = detection_rules.get_rule(rid)
    assert saved is not None
    assert "policyRoutes" not in saved["field_overrides"]


def test_create_temp_rule_proofpoint_preserves_operator_policyroutes(monkeypatch):
    """If the phase author already set ``policyRoutes`` in
    ``field_overrides`` (e.g. to override the default cluster route),
    the per-source tagging must APPEND its tokens to the operator's
    list, not replace it. Operator authorship still wins for the
    routes themselves; apigenie only adds.
    """
    import attack_scenarios
    import detection_rules

    phase = {
        "phase_id": "pp-2",
        "name":     "Proofpoint custom routes",
        "source":   "proofpoint",
        "periodicity": 3,
        "field_overrides": {"policyRoutes": ["custom_inbound", "vip_lane"]},
        "time_offset_pct": 0,
    }
    scenario = {"id": "scen-pp2", "personas": {}}
    with patch.object(attack_scenarios, "_load_scenarios",
                       return_value=[scenario]):
        rid = attack_scenarios._create_temp_rule(
            phase, attack_id="atk-pp-2", scenario_id="scen-pp2",
            total_seconds=60, phase_start=0,
        )
    assert rid
    saved = detection_rules.get_rule(rid)
    assert saved is not None
    routes = saved["field_overrides"]["policyRoutes"]
    # Operator routes preserved.
    assert "custom_inbound" in routes
    assert "vip_lane"       in routes
    # Apigenie tags appended.
    assert "apigenie-attack:atk-pp-2" in routes
    assert "apigenie-phase:pp-2"      in routes
    # Default route was NOT injected (operator overrode it).
    assert "default_inbound" not in routes
